config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index, :destroy]
  resources :people, only: [:index, :destroy]

  resources :expenses, only: [:index, :destroy, :new]
  post 'expenses/import' => 'expenses#import'

  get 'incomes/import' => 'incomes#import'
  post 'incomes/import' => 'incomes#import_func'
  resources :incomes#, only: [:index, :destroy, :new]
  #get 'expenses/:person' => 'expenses#index'


  get 'dashboard/index'
  root :to =>  'dashboard#index'

  # stfu rails
  get "/assets/bootstrap-grid.css.map" => redirect(json: 'stfu')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_aside.html.erb
<aside class="calendar-side">
  <%= month_calendar events: @calendar_event do |date, event| %>
    <%= date %>

    <% event.each do |event| %>
      <div>
        <%= event.name %>
      </div>
    <% end %>

  <% end %>

  <div class="upcoming-bills">
    <h4>Upcoming bills</h4>
    <div class="bill-content">
      <%# @calendar_event.inspect %>
      <%  @upcoming_bills.first(4).each do |event| %>
        <%# next unless (index <= 3) %>
        <div class="bill">
          <div class="bill-icon">
            <span class="<%= event.icon %>"></span>
          </div>
          <div class="bill-name">
            <strong><%= event.name %></strong>
            <p><%= event.start_time.strftime("%e %b.") %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</aside>

app/views/partials/_header.html.erb
<header class="main-header">
  <div class="side-search">
    &nbsp;
  </div>
  <h1>
    <%= link_to 'dashboard<span>project</span>'.html_safe, dashboard_index_url %>
  </h1>
  <div class="side-navigation">
    <div class="house-project">
      <%= link_to(image_tag(@current_home.photos), homes_path) %>
      <span><%= @current_home.name.upcase %></span>
    </div>
    <% if controller?("dashboard") %>
      <div class="switch-dashboard-layout">
        <a href="#" class="icon-th-large current"></a>
        <a href="#" class="icon-th-list"></a>
      </div>
    <% end %>
  </div>
</header>

app/views/partials/_nav.html.erb
<nav class="vertical-navigation">
  <ul>
    <li<%= controller?("expenses") ? ' class=selected' : '' %>>

      <%= link_to '', expenses_path, class: 'icon-money' %>
    </li>
    <li<%= controller?("incomes") ? ' class=selected' : '' %>>
      <%= link_to '', incomes_path, class: 'icon-wallet' %>
    </li>
    <li>
      <a href="#" class="icon-money-1"></a>
    </li>
    <li>
      <a href="#" class="icon-tag"></a>
    </li>
  </ul>



</nav>