config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index, :destroy]
  resources :people, only: [:index, :destroy]

  resources :expenses, only: [:index, :destroy, :new]
  post 'expenses/import' => 'expenses#import'

  get 'incomes/import' => 'incomes#import'
  post 'incomes/import' => 'incomes#import_func'
  resources :incomes#, only: [:index, :destroy, :new]
  #get 'expenses/:person' => 'expenses#index'


  get 'dashboard/index'
  root :to =>  'dashboard#index'

  # stfu rails
  get "/assets/bootstrap-grid.css.map" => redirect(json: 'stfu')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/income.rb
class Income < ApplicationRecord
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :pre_process
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  def index
    if params[:person]
      @owner = Person.find_by(name: params[:person].capitalize)
      @incomes = Income.where(owner: @owner.id)
    else
      @incomes = Income.all
    end
  end

  def new
    @income = Income.new
  end

  def import
    render 'incomes/import'
  end

  def import_func

    owner = params[:owner]
    file = params[:file_imported]
    import_from_csv(file, owner)

    redirect_to incomes_path
  end

  def edit
  end

  def create
    @income = Income.new(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to incomes_url, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def import_from_csv(file, owner)
    last_date_entry = (Income.where(owner: owner).present?) ? Income.where(owner: owner).order('date DESC').limit(1)[0].date : 0

    # Income(origin: string, owner: string, amount: float, date: date)

    csv_text = File.read(file.tempfile)
    csv = CSV.parse(csv_text, :headers => false)
    objects = []
    csv.each do |row|

      expense_date = DateTime.parse(row[0])

      next if expense_date <= last_date_entry

      object = {
          date: expense_date,
          origin: row[1],
          title: row[2],
          amount: row[3].to_f,
          owner: owner
      }
      objects << object
    end

    Income.create(objects)
    #Income.where('description LIKE ? OR description LIKE ?', '%Transfer to Desjardins Student Cash Back Visa%', '%Bill payment - AccèsD - Internet /Remises pour étudiants Vis%').destroy_all

  end

  # Use callbacks to share common setup or constraints between actions.
  def set_income
    @income = Income.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def income_params
    params.require(:income).permit(:owner, :origin, :title, :amount, :date)
  end

end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_for(income) do |f| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </div>

  <div class="field">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incomes/edit.html.erb
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income %> |
<%= link_to 'Back', incomes_path %>

app/views/incomes/import.html.erb
<h1>Import</h1>
<form class="form" action="/incomes/import" method="POST" enctype="multipart/form-data">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="form-group">
        <%= label_tag(:owner,  raw("Rapport de dépenses&nbsp;:")) %>
        <%= select_tag :owner, raw('<option value="Mathilde">Mathilde</option><option value="Virgile">Virgile</option>'), class: 'form-control' %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">

      <div class="form-group">
        <small id="emailHelp" class="form-text text-muted">Doit être un fichier CSV, séparateur: ","</small>
        <%= file_field_tag 'file_imported', class: 'form-control-file' %>
      </div>
    </div>
  </div>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="submit" class="btn btn-primary">
  <%= link_to 'Retour', incomes_path, class: 'btn btn-danger' %>
</form>

app/views/incomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Incomes<%= (@owner.present?) ? ' ('+@owner.name+')' : '' %></h1>
<% if @owner.present? %>
  <%= link_to 'Toutes', incomes_path, class: 'btn btn-info' %>
<% end %>
<%= link_to 'Mathilde', '/incomes?person=mathilde' , class: 'btn btn-info' %>
<%= link_to 'Virgile', '/incomes?person=virgile' , class: 'btn btn-info' %>
<%= link_to 'New', new_income_path, class: 'btn btn-primary' %>
<%= link_to 'Import', '/incomes/import', class: 'btn btn-primary' %>

<table id="incomes_table">
  <thead>
  <tr>
    <th>Origin</th>
    <th>Title</th>
    <th>Amount</th>
    <th>Date</th>
    <th style="width:70px;">Owner</th>
    <th style="width:20px;">&nbsp;</th>
    <th style="width:20px;">&nbsp;</th>
  </tr>
  </thead>

  <tbody>
  <% @incomes.each do |income| %>
    <% (@owner.present?) ? person = @owner : person =  Person.find(income.owner)%>
    <tr>
      <td><%= income.origin %></td>
      <td><%= income.title %></td>
      <td><%= income.amount %></td>
      <td data-sort="<%= income.date %>">
        <%= income.date.strftime("%e %b.") %>
        <% if income.date.year < Date.current.year %>
          (<%= income.date.year %>)
        <% end %>

      </td>
      <td>
        <%= image_tag person.photo %>
      </td>
      <td>
        <%= link_to '<span class="icon-edit"></span>'.html_safe, edit_income_path(income) %>
      </td>
      <td>
        <%= link_to '<span class="icon-trash"></span>'.html_safe, income, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<%# link_to 'New Expense', new_expense_path %>

<%# link_to '<span class="icon-eye-outline"></span>'.html_safe, expense %>
<%# link_to '<span class="icon-edit"></span>'.html_safe, edit_expense_path(expense) %>

app/views/incomes/new.html.erb
<%= render 'form', income: @income %>

app/views/incomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>origin:</strong>
  <%= @income.origin %>
</p>

<p>
  <strong>owner:</strong>
  <%= @income.owner %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @income.date %>
</p>

<%= link_to 'Edit', edit_income_path(@income) %> |
<%= link_to 'Back', incomes_path %>