config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index, :destroy]
  resources :people, only: [:index, :destroy]

  resources :expenses, only: [:index, :destroy, :new]
  post 'expenses/import' => 'expenses#import'

  get 'incomes/import' => 'incomes#import'
  post 'incomes/import' => 'incomes#import_func'
  resources :incomes#, only: [:index, :destroy, :new]
  #get 'expenses/:person' => 'expenses#index'


  get 'dashboard/index'
  root :to =>  'dashboard#index'

  # stfu rails
  get "/assets/bootstrap-grid.css.map" => redirect(json: 'stfu')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :person
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :pre_process
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.fetch(:home, {})
    end
end

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>
<%= link_to 'People', people_path, class: 'btn btn-primary' %>

<table id="homes_table">
  <thead>
  <tr>
    <th>Photo</th>
    <th>Name</th>
    <th>Address</th>
    <th>People</th>
    <th style="width:20px;">&nbsp;</th>
  </tr>
  </thead>

  <tbody>
  <% @homes.each do |home| %>
    <tr>
      <td><%= image_tag home.photos %></td>
      <td><%= home.name %></td>
      <td><%= home.address %></td>
      <td>
        <% people = Person.where(home_id: home.id) %>
        <% if people.count > 0 %>
            <% people.each do |person| %>
                <%= image_tag person.photo, style: 'width: 30px; height: 30px;' %>
                <%= person.name %>
            <br>
            <% end %>
        <% end %>
      </td>
      <td>        &nbsp;
        <%= link_to '<span class="icon-trash"></span>'.html_safe, home, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>


<%# link_to 'New Expense', new_expense_path %>

<%# link_to '<span class="icon-eye-outline"></span>'.html_safe, expense %>
<%# link_to '<span class="icon-edit"></span>'.html_safe, edit_expense_path(expense) %>